import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Bookmark, BookmarkCheck, Mail, Download } from 'lucide-react';

const RoundBar = ({ label, score }) => {
  const color = score >= 80 ? 'bg-success' : score >= 60 ? 'bg-warning' : 'bg-danger';
  const textColor = score >= 80 ? 'text-success' : score >= 60 ? 'text-warning' : 'text-danger';

  return (
    <div className="mb-3">
      <div className="mb-1 flex justify-between text-xs">
        <span className="text-slate-500">{label}</span>
        <span className={`font-bold ${textColor}`}>{score || 0}%</span>
      </div>
      <div className="h-1.5 overflow-hidden rounded-full bg-slate-100">
        <motion.div
          initial={{ width: 0 }}
          animate={{ width: `${score || 0}%` }}
          transition={{ duration: 0.8, ease: 'easeOut' }}
          className={`h-full rounded-full ${color}`}
        />
      </div>
    </div>
  );
};

export default function StudentProfileModal({ student, onClose, onShortlist }) {
  if (!student) return null;

  const handleDownload = () => {
    const content = `eraAI Candidate Report
======================
Name: ${student.name}
Email: ${student.email}
College: ${student.college || 'N/A'}
Stream: ${student.stream || 'N/A'}
Tier: ${student.tier || 'N/A'}
Year: ${student.year || 'N/A'}

SCORES
------
Overall: ${student.scores?.overall || 0}%
Round 1: ${student.scores?.round1 || 0}%
Round 2: ${student.scores?.round2 || 0}%
Round 3: ${student.scores?.round3 || 0}%
Round 4: ${student.scores?.round4 || 0}%

Rounds Completed: ${student.roundsCompleted?.length || 0}/4
Badges: ${student.badges?.join(', ') || 'None'}

Generated by eraAI`.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${student.name.replace(/\s+/g, '_')}_eraAI_report.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const overall = student.scores?.overall || 0;
  const scoreColor = overall >= 80 ? 'text-success' : overall >= 60 ? 'text-warning' : 'text-danger';

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 px-4 backdrop-blur-sm"
        onClick={onClose}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.92, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.92 }}
          transition={{ type: 'spring', damping: 25 }}
          className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-[26px] border border-sky-100 bg-[#fcfeff] shadow-[0_16px_40px_rgba(15,23,42,0.12)]"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="flex items-start justify-between border-b border-sky-100 p-6">
            <div className="flex items-center gap-4">
              <div className="flex h-14 w-14 items-center justify-center rounded-full border border-sky-100 bg-gradient-to-br from-sky-50 to-violet-50 text-xl font-black text-sky-600">
                {student.name?.charAt(0)}
              </div>
              <div>
                <h2 className="text-lg font-black text-slate-900">{student.name}</h2>
                <p className="text-sm text-slate-600">{student.email}</p>
                <p className="text-xs text-slate-500">
                  {student.college}
                  {student.year ? ` • ${student.year}` : ''}
                </p>
              </div>
            </div>
            <button onClick={onClose} className="mt-1 text-slate-400 transition-colors hover:text-slate-700">
              <X size={18} />
            </button>
          </div>

          <div className="space-y-5 p-6">
            <div className="flex items-center justify-between rounded-2xl border border-sky-100 bg-[#f8fbff] p-4">
              <div>
                <p className="text-xs text-slate-500">Overall eraAI Score</p>
                <p className={`mt-0.5 text-3xl font-black ${scoreColor}`}>{overall}%</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500">Rounds Completed</p>
                <p className="text-lg font-bold text-slate-900">{student.roundsCompleted?.length || 0}/4</p>
                <div className="mt-1 flex justify-end gap-1">
                  {[1, 2, 3, 4].map((r) => (
                    <div key={r} className={`h-2.5 w-2.5 rounded-full ${student.roundsCompleted?.includes(r) ? 'bg-success' : 'bg-slate-200'}`} />
                  ))}
                </div>
              </div>
            </div>

            <div className="flex flex-wrap gap-2">
              {student.stream && <span className="rounded-full border border-sky-200 bg-sky-50 px-2.5 py-1 text-xs text-sky-700">{student.stream}</span>}
              {student.tier && <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-600">{student.tier}</span>}
              {student.state && <span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-600">{student.state}</span>}
            </div>

            <div>
              <p className="mb-3 text-sm font-semibold text-slate-900">Score Breakdown</p>
              <RoundBar label="Round 1 - MCQ" score={student.scores?.round1} />
              <RoundBar label="Round 2 - Written" score={student.scores?.round2} />
              <RoundBar label="Round 3 - Video" score={student.scores?.round3} />
              <RoundBar label="Round 4 - Advanced" score={student.scores?.round4} />
            </div>

            {student.badges?.length > 0 && (
              <div>
                <p className="mb-2 text-sm font-semibold text-slate-900">Achievements</p>
                <div className="flex flex-wrap gap-2">
                  {student.badges.map((b, i) => (
                    <span key={i} className="rounded-full border border-violet-200 bg-violet-50 px-2.5 py-1 text-xs text-violet-600">{b}</span>
                  ))}
                </div>
              </div>
            )}

            <div className="flex gap-2 pt-2">
              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => onShortlist(student._id, student.isSaved)}
                className={`flex flex-1 items-center justify-center gap-1.5 rounded-xl border py-2.5 text-sm font-semibold transition-all ${
                  student.isSaved ? 'border-sky-200 bg-sky-50 text-sky-700' : 'border-sky-200 text-sky-700 hover:bg-sky-50'
                }`}
              >
                {student.isSaved ? <BookmarkCheck size={14} /> : <Bookmark size={14} />}
                {student.isSaved ? 'Shortlisted' : 'Shortlist'}
              </motion.button>

              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => window.open(`mailto:${student.email}?subject=Interview Invitation from eraAI&body=Hi ${student.name},%0D%0A%0D%0AWe are impressed with your eraAI assessment scores and would like to invite you for an interview.%0D%0A%0D%0ARegards`)}
                className="flex flex-1 items-center justify-center gap-1.5 rounded-xl border border-violet-200 py-2.5 text-sm font-semibold text-violet-600 transition-all hover:bg-violet-50"
              >
                <Mail size={14} /> Invite
              </motion.button>

              <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleDownload}
                className="flex items-center justify-center gap-1.5 rounded-xl border border-sky-100 px-4 py-2.5 text-sm font-semibold text-slate-600 transition-all hover:bg-[#f7fbff] hover:text-slate-900"
              >
                <Download size={14} />
              </motion.button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
